name: Push Model to Replicate

on:
  workflow_dispatch:
jobs:
  push_to_replicate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # Install Git and Git LFS for model handling
      - name: Install Git and Git LFS
        run: |
          sudo apt update
          sudo apt install -y git git-lfs
          git lfs install

      # Disk space cleanup steps
      - name: Cleanup unused docker images
        run: |
          sudo apt autoremove --purge
          sudo apt autoclean
          sudo apt clean
          docker system prune -af

      - name: CleanUp hostedtoolcache
        run: rm -rf /opt/hostedtoolcache

      - name: Free disk space
        run: |
          chmod +x ./script/free_disk_space.sh
          ./script/free_disk_space.sh
        shell: bash

      # Download models using the custom script
      - name: Download Models
        run: |
          chmod +x ./script/download_models.sh
          ./script/download_models.sh
        shell: bash

      # Install Cog
      - name: Install Cog
        run: |
          sudo curl -o /usr/local/bin/cog -L https://github.com/replicate/cog/releases/download/v0.8.0-beta3/cog_Linux_x86_64
          sudo chmod +x /usr/local/bin/cog
          cog --version

      # Log in to Replicate
      - name: Log in to Replicate
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
        run: |
          echo $REPLICATE_API_TOKEN | cog login --token-stdin

      - name: Push to Replicate
        run: cog push r8.im/jweek/mask_maker
